server:
  port: 4396


spring:

  datasource:
    username: root
    password: 123456
    jdbc-url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema:
      - classpath:schema.sql
      # 数据
    data:
      - classpath:data.sql
    separator: ; #; 为sql脚本中语句分隔符
    sql-script-encoding: utf-8 #utf-8 为文件的编码
    initialization-mode: always  #always为始终执行初始化，embedded只初始化内存数据库（默认值）,如h2等，never为不执行初始化。
    continue-on-error: true

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
